services:
  mongoose-graphql-auth:
    build:
      context: .
      target: development
    command: pnpm run start:dev
    env_file:
      - .env
    ports:
      - '4000:4000'
    volumes:
      - .:/usr/src/app
  mongo:
    image: mongo
